version: '3'
services:
  db_test:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./.env
    ports:
      - 3306:3306
    networks:
      - network_db
    expose:
      - 3306

  app_test:
    build:
      context: .
      dockerfile: ./django/Dockerfile.test
    ports:
      - 80:8000
    expose:
      - 80
    networks:
      - network_db
    links:
      - db_test:db
    env_file:
      - ./.env
    depends_on:
      - db_test
    command: sh -c "/scripts/wait && /scripts/docker-entrypoint.sh"
    volumes:
      - ./etitango:/etitango

volumes:
  mysql_data:

networks:
  network_db:
    driver: bridge