version: '3'
services:
 db:
  build:
    context: .
    dockerfile: ./mysql/Dockerfile
  restart: always
  command: mysqld --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_DATABASE: 'db_etitango'
   MYSQL_USER: 'etitango'
   MYSQL_PASSWORD: 'etitango'
   MYSQL_ROOT_PASSWORD: 'pgpadmin'
  ports:
   - 3306:3306
  expose:
   - 3306

 etitango:
   build: .
   restart: always
   ports:
    - 8000:8000
   expose:
     - 8000
   links:
     - db:db
   env_file: etitango/etitango/.env
   environment:
     DEBUG: "true" # Must change for ops
   depends_on:
    - db
   command: sh -c "/wait && /docker-entrypoint.sh"
   environment:
     - WAIT_HOSTS=db:3306
     - WAIT_HOSTS_TIMEOUT=5
     - WAIT_SLEEP_INTERVAL=15
     - WAIT_HOST_CONNECT_TIMEOUT=5
   # volumes:
     # - ./etitango:/var/www/html/etitango
