version: '3'
services:
  db_prod:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./.env.prod  
    ports:
      - 3306:3306
    networks:
      - network_db
    expose:
      - 3306

  app_prod:
    build: .
    restart: always
    # ports:
      # - 8000:8000
    expose:
      - 8000
    networks:
      - network_proxy
      - network_db
    links:
      - db_prod:db
    env_file:
      - ./.env.prod
    depends_on:
      - db_prod
    command: sh -c "./scripts/wait && ./scripts/docker-entrypoint.sh"
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media

  proxy_prod:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    ports:
      - "80:80"
      - "443:443"
    links:
      - app_prod:etitango
    networks:
      - network_proxy
    depends_on:
      - app_prod
  
volumes:
  static_data:
  media_data:
  mysql_data:

networks:
  network_proxy:
    driver: bridge
  network_db:
    driver: bridge
