version: '3'
services:
  db_dev:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./.env  
    ports:
      - 3306:3306
    networks:
      - network_db
    expose:
      - 3306

  app_dev:
    build: .
    restart: unless-stopped
    ports:
      - 80:8000
    # expose:
      # - 8000
    networks:
      - network_proxy
      - network_db
    links:
      - db_dev:db
    env_file:
      - ./.env
    depends_on:
      - db_dev
    command: sh -c "./scripts/wait && ./scripts/docker-entrypoint.sh"
    volumes:
      - app_data:/vol/web

  proxy_dev:
    build:
      context: ./proxy
    restart: unless-stopped
    volumes:
      - ./proxy/conf.d/:/etc/nginx/conf.d
      - app_data:/var/www/html
    ports:
      - "1337:80"
    links:
      - app_dev:app_dev
    networks:
      - network_proxy
    depends_on:
      - app_dev

volumes:
  app_data:
  mysql_data:

networks:
  network_proxy:
    driver: bridge
  network_db:
    driver: bridge