version: '3'
services:
 db:
  image: mysql:latest
  restart: always
  command: mysqld --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_DATABASE: 'db_etitango'
   MYSQL_USER: 'etitango'
   MYSQL_PASSWORD: 'etitango'
   MYSQL_ROOT_PASSWORD: 'pgpadmin'
  ports:
   - 3306:3306
  expose:
   - 3306

 etitango:
   build: .
   restart: always
   ports:
    - 8000:8000
   expose:
     - 8000
   links:
     - db:db
   env_file: etitango/etitango/.env
   environment:
     DEBUG: "true" # Must change for ops
   depends_on:
    - db
   command: sh -c "/wait && python3 /var/www/html/etitango/manage.py runserver 0.0.0.0:8000"
   environment:
     - WAIT_HOSTS=db:3306
     - WAIT_HOSTS_TIMEOUT=15
     - WAIT_SLEEP_INTERVAL=15
     - WAIT_HOST_CONNECT_TIMEOUT=15
   volumes:
     - ./etitango:/var/www/html/etitango
